
package UI;
import java.awt.Graphics;
import java.util.LinkedList;
import truss.*;

/**
 *
 * @author Wislo
 */
public class CreateTruss extends javax.swing.JPanel {
    private LinkedList<Joint> addedJoints;
    private LinkedList<Member> addedMembers;
    private LinkedList<PinnedSupport> addedPins;
    private LinkedList<RollerSupport> addedRollers;
    
    private ButtonPanel btnPanel;
    private EditorPanel edPanel;
    
    private int noJoints;
    private int noMembers;
    
    
    
    /**
     * Creates new form CreateTruss
     */
    public CreateTruss() {
        initComponents();
        this.addedJoints = new LinkedList<>();
        this.addedMembers = new LinkedList<>();
        this.addedPins = new LinkedList<>();
        this.addedRollers = new LinkedList<>();
        
        this.noJoints = 0;
        this.noMembers = 0;
        
        
        this.btnPanel = new ButtonPanel(this);
        this.edPanel = new EditorPanel(this);
        this.add(btnPanel);
        this.add(edPanel);
        edPanel.addButtonPanel(btnPanel);
        btnPanel.setEditorPanel(edPanel);
        
    }
    
    public void addJoint(Joint joint){
        this.noJoints++;
        joint.setName("J"+(noJoints));
        this.addedJoints.add(joint);
    }
    
    public void addMember(Member member){
        this.noMembers++;
        member.setName("M"+noMembers);
        this.addedMembers.add(member);
    }
    
    public LinkedList<Joint> getAddedJoints(){
        return this.addedJoints;
    }
    
    public LinkedList<Member> getAddedMembers(){
        return this.addedMembers;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
